### ISSUE TITLE
UI unification

### ISSUE THREAD

**Issue by hmil** [lbarman/vaultage#103]
**Situation**: There are two competing web UIs (GUI and CLI).  
**Problem**:
1. We can't maintain two separate UIs given our development resources
2. A user will be confused if presented with two distinct UI choices

**Solutions**:
1. Chose one UI and get rid of the other
2. Unify the UIs into a single interface (like: defaults to GUI but with a button "show console" to switch to CLI mode)

cf. https://github.com/lbarman/vaultage/blob/e915bee45870489db8abfcebdcafe4d791a1157f/packages/vaultage/src/main.ts#L59

**Comment by lbarman** [comment]
I see. Well, they are not competing; we have one UI (CLI), and one dead-simple UI meant as a backup (GUI) in case *something* goes wrong with the main UI. I'd advocate that we (I) can maintain the backup gui easily.

Perhaps the question is whether we want to package it with the main `vaultage` server by default. In my current setup, I have it on a separate server (lbarman.ch), not maintained whatsoever; but it already happened to me that I had to use it when my mobile would not let me interact with the CLI (admittedly, since our new CLI is wonderful, this should not happen again).

Let's discuss / keep this open. Perhaps we can delete the simple UI

**Comment by hmil** [comment]
IDK what the GUI looks like but one option then is to show the user-friendly GUI by default at the root '/' and show the unmodified CLI at '/cli'. Then we add a link in the GUI that points to the CLI so geeky users can switch to the 1337-enabled UI.
Simple enough for me.
I'm only concerned about the burden of maintaining both.

**Comment by lbarman** [comment]
`user-friendly GUI` which one is that ? we have only one functional GUI, `cli`. The other, simple backup GUI does not provide all functions, it only decrypts and displays passwords.

But yes, I agree with the approach
