### ISSUE TITLE
Make vaultage-web-cli show the current npm package version instead of "v4.0"

### ISSUE THREAD

**Issue by lbarman** [lbarman/vaultage#130]

**Comment by hmil** [comment]
vaultage-**web**-cli ?

**Comment by lbarman** [comment]
yep

**Comment by lbarman** [comment]
@hmil any idea how to do this ? This would be actually useful - to be able to check in the WebUI that we're running `4.2.1` or `4.2.0`

My first shot was to edit `packages/vaultage/bin/vaultage.js` and add something like:

``` 
var path = require("path");
var exec = require('child_process').exec;

var cmd = 'npm list -g vaultage | tail -n 2 | head -n 1';

exec(cmd, function(error, stdout, stderr) {
  var configFolder = path.dirname('~/.vaultage');
  // write stdout into configFolder/.version
}); ```

But it has multiple problems:
1. how to read it from the GUI (not only from the vaultage-server)
2. what if you run the package locally without having it `-g`lobally installed

**Comment by hmil** [comment]
You can get the version in the client and the server by doing (approximately):
`const { version } = require('../package.json');`

If you want the server version on the client (they should be the same but for the sake of debugging it's better to show both), then you should add an API endpoint such as `/version` which returns the `version` variable defined above.

Then to make things clean it might be a good idea to wrap this API call in the client library:
`vaultage.getServerVersion((err, version) => ...);`

In dev you will see `0.0.0` or whatever the placeholder `version` is in all package.json files. One caveat is we must make sure the deployment scripts first sets the correct version and then builds the client. Otherwise the client will be built with the development version number (0.0.0)

**Comment by lbarman** [comment]
Done https://github.com/lbarman/vaultage/pull/144

**Comment by hmil** [comment]
#144 was not merged, re-opening
