### ISSUE TITLE
Restrict listening interface + cli option

### ISSUE THREAD

**Issue by hmil** [lbarman/vaultage#154]
`vaultage-server` should listen to `localhost` or `127.0.0.1` by default and include a CLI option to specify another interface. For instance `vaultage-server -l 192.168.0.1`.

Not sure what the best practice here is.

cc @christophetd

**Comment by christophetd** [comment]
The good practice to avoid any form of DNS rebinding is to check, for every HTTP request, that the `Host` header matches the interface on which the server was bound to listen.

- `vaultage-server -l 127.0.0.1` should only accept requests with a `Host: 127.0.0.1` or `Host: localhost`
- `vaultage-server -l 1.2.3.4` should only accept requests with a `Host: 1.2.3.4`
- `vaultage-server -l 0.0.0.0` should allow any `Host` value

**Comment by lbarman** [comment]
Interesting; just to bring me up to speed, can you provide an attack example? in particular does it relies on having autofill enabled for passwords ?

**Comment by christophetd** [comment]
cf. https://blog.scrt.ch/2011/11/22/dns-rebinding-java/ https://en.wikipedia.org/wiki/DNS_rebinding

**Comment by lbarman** [comment]
I read it, thanks. Yet how is this attack started in the first place, does the Vaultage server have to be malicious to send javascript (=> game is lost anyway) ? does the malicious script come from a third party (chrome extention ?)

I am also eager to fix practical issues, but I don't see how it fits the threat model; if an attacker manages to run code on the server/the client, it's over. Please enlighten me :)

**Comment by christophetd** [comment]
Nope, an example of a DNS rebinding attack would be a malicious _attacker-controlled_ website which resolves alternatively to 127.0.0.1, and alternatively to the attacker-controller webserver (e.g. 10.10.10.10). Assume `/doStuff` is a sensitive action on Vaultage's API server. When a Vaultage user visits the malicious website, this website would include some JS code making a request to `/doStuff`, which at some point would resolve to `127.0.0.1/doStuff`. The browser would send authentication cookies along with the request (since it's the same origin), meaning that even if the action is cookie-authenticated it can be exploited.

(Sorry for the sketchy explanation - see a @taviso bug report as an example https://bugs.chromium.org/p/project-zero/issues/detail?id=1471)

**Comment by lbarman** [comment]
There is no server running on localhost in Vaultage - does it target the remote vaultage server ?
(I have other comments but want to nail down the attack before going on ;) )

Let me try:
```
1. Honest user is authenticated into vaultage (he has a tab opened with the vaultage client)
2. Honest user visit evil.com, which resolves to evil_ip, loads a website with some malicious js
3. the malicious scripts sends a query to vaultageserver.com/doStuff
4. ???
```

**Comment by christophetd** [comment]
```
3. The malicious script sends a request to vaultageserver.com/dumpPasswords
4. The malicious script steals your passwords
```

**Comment by lbarman** [comment]
3. Requests are only valid if they contain the `REMOTE_KEY`. How did the malicious script learn it ?

**Comment by christophetd** [comment]
I'm not familiar with how the vaultage client / server interaction works. If it's not based on cookies, I'd say DNS rebinding shouldn't be too much of an issue indeed.

**Comment by lbarman** [comment]
Thanks. Still, some authentication information are cached, but at the client's, and I struggle to see how you could use DNS rebinding to extract them (without compromizing the server)
@hmil ?

**Comment by hmil** [comment]
I think the attacker could attempt to bruteforce the remote key. We do not store any sensitive information anywhere else than in the open tab's memory*. However I still don't get how DNS rebinding bypasses cookie-based auth. If your cookie is tied to `vaultageserver.me`, a request to `evil.ru` will never send that cookie even if `host evil.ru` === `host vaultageserver.me`.

---
*note to self: Do browsers zero-out the memory they free? Write a javascript file which floods the tab's memory with a canary, close the browser, then spin up a C program which mallocs insane amounts of memory and searches for the canary. Solution: array-backed strings which clear themselves on `beforeunload` o/

**Comment by lbarman** [comment]
My understanding is that the attack works the opposite way. 

You have a LAN with a router on IP `192.168.0.1` that allows the config only from inside the LAN. The honest client visits `evil.com`. `Evil.com` cannot send a JS that queries `192.168.0.1` via AJAX (even if network-wise it would be OK) because the browser detects that you are on `evil.com` and that you're trying to access another IP/Domain; hence the browser blocks the query.

That's where you DNS-rebind `evil.com` mid-process to `192.168.0.1`, so when the AJAX is performed, `evil.com` (which expired in the cache in the meantime due to short TTL) is resolved to the `192.168.0.1`. The browser happily let the request through.

This does not seem applicable to vaultage

**Comment by lbarman** [comment]
``` *note to self: Do browsers zero-out the memory they free? Write a javascript file which floods the tab's memory with a canary, close the browser, then spin up a C program which mallocs insane amounts of memory and searches for the canary. Solution: array-backed strings which clear themselves on beforeunload o/```

The vaultage-client (and its computer) is trusted ;)

**Comment by hmil** [comment]
> My understanding is that the attack works the opposite way.
... The browser happily let the request through.

Yes except the browser sends `evil.com`'s cookies to 192.168.0.1, not the other way around.

**Comment by hmil** [comment]
> The vaultage-client (and its computer) is trusted ;)

Is nonetheless tend to prefer when unprivileged processes cannot steal my stuff.

**Comment by lbarman** [comment]
right... so the honest website gets the cookie of the dishonest site ? isn't that backwards too ? :p

**Comment by hmil** [comment]
¯\_(ツ)_/¯

**Comment by christophetd** [comment]
> Evil.com cannot send a JS to the client that queries 192.168.0.1/changePassword via AJAX (even if network-wise it would be OK) because the browser detects that you are on evil.com and that you're trying to access another IP/Domain; hence the browser blocks the query.

What you're saying is `The Same Origin Policy prevents a JS code from reading data from another domain`, and you're right. But in DNS rebinding, _the origin is the same_ - it's the IP to which the origin resolve which changes, and the browser has no check for this.

Regardless of how the Vaultage API is implemented, if I run the Vaultage server bound to `127.0.0.1`, I expect that only I should be able to access it from my local interface (even if it's authenticated or whatever). And in order to enforce that, the `Host` header needs to be validated to prevent DNS rebinding

**Comment by lbarman** [comment]
```
Is nonetheless tend to prefer when unprivileged processes cannot steal my stuff.
```
I'll open a PR to rewrite vaultage on open source arm infrastructure ;)

**Comment by lbarman** [comment]
```
Regardless of how the Vaultage API is implemented, if I run the Vaultage server bound to 127.0.0.1, I expect that only I should be able to access it from my local interface (even if it's authenticated or whatever). And in order to enforce that, the Host header needs to be validated to prevent DNS rebinding
```
Thanks for the explanation, it's clear now. I agree; it's non-critical, but we should fix it.

**Comment by hmil** [comment]
As I understand DNS rebinding is orthogonal to ip binding. I'll open another issue for this one. Thx @christophetd

**Comment by christophetd** [comment]
Makes sense - if the vaultage server doesn't restrict the IP on which it listens, there's no point in DNS rebinding to start with since the server can be accessed publicly
