### ISSUE TITLE
Derive local and remote pwds from master key

### ISSUE THREAD

**Issue by hmil** [lbarman/vaultage#51]
This is not less secured than having two distinct passwords and may even be more secured if the user is inexperienced.

Idea:
```
       masterKey
          |
   s -> [hash]
          |
          +------------+
          |            |
   s1 ->[hash]      [hash] <- s2
          |            |
      local key      remote key
```

Also:
- Use many rounds of hashing with a healthy dose of salt ( this needs be done only once in the client so it better be computationally expensive)

**Comment by lbarman** [comment]
I also checked stuff like PBKDF2 which have nice properties (probably those which you refer to, e.g. derivating the hash is intentionnally slow and expensive), the problem is that their implementation in JS is often not really vetted. If you find something trustworthy, it's perfect, let's go for it.
Otherwise, I'll stick to well-known algorithm in well-known crypto libs.
