### ISSUE TITLE
Unclear: Use of PBKDF2 as chaining primitive

### ISSUE THREAD

**Issue by lbarman** [lbarman/vaultage#67]
@hmil We already had the discussion, but I'm again unclear why we changed the update message from

CREDENTIALS | CIPHER(NEW_DB) | HASH(OLD_DB)

by

CREDENTIALS | CIPHER(NEW_DB) | PBKDF2(OLD_DB, Local password)

I think you're trying to protect when an attacker learns RemotePwd, but not LocalPwd, and tries to erase the server DB. However, I think the hash of the plaintext old DB achieves the same thing, while being easier to understand, and faster. Chaining with hash is natural (blockchains), and also proves the knowledge of "Local password" since performed upon the plaintext db.

**Comment by hmil** [comment]
It may be a relique from when the remote and local keys weren't necessarily derived from the same master password. In such a case, if one pushes a DB encrypted with a new local password, then an out-of-sync client could overwrite it with the old local password because the local password doesn't change the DB's plaintext.

See the comments [here](https://github.com/lbarman/vaultage/blob/f46907772191d96b7f9ecd11a4a97d2a71d5d872/packages/js-sdk/vaultage.ts#L315)

**Comment by lbarman** [comment]
Interesting, I haven't thought of that. Let's keep it this way then
