### ISSUE TITLE
UUID instead of numerical IDs ?

### ISSUE THREAD

**Issue by lbarman** [lbarman/vaultage#95]
@hmil , why did we go from numerical IDs like `33`, `34`, `35` to UUID like `f00f79aa-71b7-81a3-d7e9-6430254d9df5` ?

It makes functions like `edit 15`, `rm 15` much less user friendly (`edit f00f79aa-71b7-81a3-d7e9-6430254d9df5`)

**Comment by hmil** [comment]
true that. UUIDs are just cleaner to generate because you don't have to store the auto_increment counter in the DB. On the other hand ids are never user friendly and I'd lean towards not exposing them at all.

I see two options:
- Implement an auto_increment in the VaultDB
- Change the CLI functions to accept names instead of ids. For instance:
```
> ls
- GoT      : john@winterfell.north ****
- simpsons : homer@springfield.com ****
- simpsons : maggie@springfield.com ****
> rm GoT
removing: GoT (john@winterfell.north)
> rm simpsons
Mutliple candidates found:
1. simpsons (homer@springfield.com)
2. simpsons (maggie@springfield.com)
Which one to delete ? 1
removing: simpsons (homer@springfield.com)
```

**Comment by lbarman** [comment]
Fixed with `v4`
